### ISSUE TITLE
Ensure all containers are ready to go on start

### ISSUE THREAD

**Issue by a-s-o** [a-s-o/log-api#2]
- [x] kafka
- [ ] zookeeper
- [x] postgres

Try removing the containers; running `setup` and then `start`. There are some connection issues where the containers have not fully initialized.

Example

```
SequelizeConnectionError: Connection terminated
    at /home/aman/Code/log-api/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:78:18
    at null.<anonymous> (/home/aman/Code/log-api/node_modules/pg/lib/client.js:184:7)
    at g (events.js:260:16)
    at emitNone (events.js:67:13)
    at emit (events.js:166:7)
    at Socket.<anonymous> (/home/aman/Code/log-api/node_modules/pg/lib/connection.js:66:10)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)
```

**Comment by a-s-o** [comment]
Done in 197bbec16eaf805ad0b8a787058230308107b033

No zookeeper checks for now as it is reasonably expected to start before the kafka hasBroker checks complete.
